
# This file is automatically generated by setup.py, So don't edit it. :)
version_info = {
    'branch_nick': 'master',
    'revision_id': 'd8c54cb4b63f78b27c6141ec66e50c6b52076f9b',
    'revno': 1351
}
